---
# Install the collection:   ansible-galaxy collection install -r requirements.yml
# Install the Python dep:    pip install pan-os-python
collections:
  - name: paloaltonetworks.panos
    version: ">=2.20.0"
